Image Class Reference
The Image class is the abstraction of the image, contains a CImg object that defines the handling of the image.
#include <ParallelPic.hh>
Public Member Functions
Image ()
Constructor This constructor initializes the four dimension params at 0; The Img calls the constructor of CImg to create an empty image.
Image (const char *const filename)
Image() is the constructor of the image used when the image doesn't been be created.
Image (const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, int value)
Image (const char *const filename) this constructor is used when the image already exist's and is stored in.
~Image (void)
void display (const char *message)
void set_pixel_value (int x, int y, int z, int c, unsigned char)
Image substract_img (Image, int)
This function substracts the pixel values of two images, that can be used to see the differences between them.
Image sum_img (Image, int)
Image multiply_img (double, int)
This function multiplies the pixel values by a factor. If the pixel value is higher than 255, adjust the pixel value to 255.
Image binarize_img (unsigned int, int)
Image filter_Laplacian (int)
Returns an image after applying the Laplacian filter to the image. Considers the diagonal values This function applies a convolution with this kernel: $ ((1, 1, 1), (1, -8, 1), (1, 1, 1)) $.
Image filter_Laplacian_no_diagonal (int)
Image filter_Gradient_vertical (int)
Image filter_Gradient_horizontal (int)
Image filter_Prewitt_N_S (int)
Image filter_Prewitt_NE_SW (int)
Image filter_Prewitt_E_W (int)
Image filter_Prewitt_NW_SE (int)
Image filter_edge_enhacement_displacement (unsigned int, unsigned int, int)
Image filter_horizontal_borders (int)
Image filter_vertical_borders (int)
Image filter_median (int, int)
This function calculates the median of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Image filter_average (int, int)
This function calculates the average of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Image average_omp (int, int)
Image filter_gaussian (int, int, int)
This function applies a gaussian kernel trough the hole image.
Image filter_modal (int, int)
This function calculates the modal of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Image median_omp (int, int)
Image filter_dynamic_range_dilatation (unsigned char, unsigned char, double, double, double, int)
All the pixel values are divided in 3 ranges, and each range suffer a diferent transformation. This function is used to transform the range of lower pixel values in medium values and the higher too, to smooth the image.
Image inverse (int)
Image log_transformation (int)
Image power_law_transformatiom (double exponent, int)
Executes this transformation: $ v(x,y,z,c) = c log(u(x,y,z,c)+1)$.
Image color_slicing (unsigned char[], unsigned char[], unsigned char[], int)
Highlights the desired colors, between the two colors given as parameters.
int * get_histogram (unsigned int c, unsigned int z)
void plot_histogram (int, const char *title)
This function plot the histogram, using the CImg histogram function.
int * histogram_equalization (int *, const char *title)
CImg< float > autocovariance (int, int, int)
Calculates the autocovariance matrix for the image. The covariance, calculates the covariance matrix of an image. This function calculates something similar to the function below: $ g(x,y) = \sum \limits_{n=0}^{N} \sum \limits_{m=1}^M \left( f(x,y) - \overline{f(x,y)}\right)\left(f(x + \Delta x, y + \Delta y) - \overline{f(x + \Delta x, y + \Delta y)} \right) $ Where it calculates the variation between two series, one is the normal one, and the other is displaced by two parameters $ x$ & $ y$. For an image it its calculated for a neighborhood around each pixel.
void plot_histogram_equalization (int, const char *title)
Image filter_order_stadistics (int dim, int order, int)
Image variance (int, int)
This function compute the variance of an image. The variance is gived by the summation of the average multiplied by the substraction of the average with the pixel value, squared.
Image filter_kirsch_0 (int)
Applies the kirsch mask at 0°. $(-3,-3,5)(-3,0,5)(-3,-3,5)$.
Image filter_kirsch_45 (int)
Applies the kirsch mask at 45°. $(-3,5,5)(-3,0,5)(-3,-3,-3)$.
Image filter_kirsch_90 (int)
Applies the kirsch mask at 90°. $(5,5,5)(-3,0-3)(-3,-3,-3)$.
Image filter_kirsch_135 (int)
Applies the kirsch mask at 135°. $(5,5,-3)(5,0,-3)(-3,-3,-3)$.
Image filter_kirsch_180 (int)
Applies the kirsch mask at 180°. $(5,-3,-3)(5,0,-3)(5,-3,-3)$.
Image filter_kirsch_225 (int)
Applies the kirsch mask at 225°. $(-3,-3,-3)(5,0,-3)(5,5,-3)$.
Image filter_kirsch_270 (int)
Applies the kirsch mask at 270°. $(-3,-3,-3)(-3,0,-3)(5,5,5)$.
Image filter_kirsch_315 (int)
Applies the kirsch mask at 315°. $(-3,-3,-3)(-3,0,5)(-3,5,5)$.
Image filter_freeman_0 (int)
Applies the freeman mask $(1,1,1)(1,-2,1)(1,-1,-1)$.
Image filter_freeman_1 (int)
Applies the freeman mask $(1,1,1)(-1,-2,1)(1,-1,1)$.
Image filter_freeman_2 (int)
Applies the freeman mask $)-1,1,1)(-1,-2,1)(1,1,1)$.
Image filter_freeman_3 (int)
Applies the freeman mask $(-1,-1,1)(-1,-2,1)(1,1,1)$.
Image filter_freeman_4 (int)
Applies the freeman mask $(-1,-1,-1)(1,-2,1)(1,1,1)$.
Image filter_freeman_5 (int)
Applies the freeman mask $(1,-1,-1)(1,-2,-1)(1,1,1)$.
Image filter_freeman_6 (int)
Applies the freeman mask $(1,1,-1)(1,-2,-1)(1,1,-1)$.
Image filter_freeman_7 (int)
Applies the freeman mask $(1,1,1)(1,-2,-1)(1,-1,-1)$.
Image filter_maximum (int)
Assigns the highest value in the neighborhood. Assigns the highest value in the neighborhood around the desired pixel.
Image filter_minimum (int)
Assigns the highest value in the neighborhood.
Image gray_scale (int)
Assigns the lowest value in the neighborhood.
void gaussian_noise (double, int)
Converts an RGB image to gray scale.
void salt_pepper (double, int)
Put pepper (black pixels) and salt(white pixels)
Image interpolation (int)
This function doubles the size of the image and use the closer neighborhood interpolation.
Image coorrelogram (unsigned int, unsigned int, int)
This function compute the coorrelogram of an image.
Image coorrelogram_ZC (unsigned int, unsigned int, unsigned int, unsigned int, int)
Image coorrelogram_par (unsigned int, unsigned int, unsigned int, unsigned int)
Image rgb_hsv ()
Detailed Description
The Image class is the abstraction of the image, contains a CImg object that defines the handling of the image.
This class have the attributes of the four dimensions of the image: height, width, depth and spectrum
Definition at line 21 of file ParallelPic.hh.
Constructor & Destructor Documentation
Image::Image ()
Constructor This constructor initializes the four dimension params at 0; The Img calls the constructor of CImg to create an empty image.
Definition at line 17 of file image.cpp.
{
    this->Img = new CImg<unsigned char>();
    this->width = 0;
    this->height = 0;
    this->depth = 0;
    this->spectrum = 0;
}
Image::Image (const char *const filename)
Image() is the constructor of the image used when the image doesn't been be created.
Constructor.
This constructor is used when the image already exist's and is stored in the
Parameters
filename path.
Parameters
<Img> is a var of type Cimg that is treated like an unsigned char.
<width> refers to the number of columns of pixels in the image.
<height> refers to the number of rows of pixels in the image.
<depth> is the amount of layers of depth the image has, usually is one, except for 3D images.
<spectrum> is the number of channels in the image, RGB has a spectrum of 3, a monocromatic image has a spectrum of 1.
Definition at line 32 of file image.cpp.
{
    this->Img = new CImg<unsigned char>(filename);
    this->width = this->Img->width();
    this->height = this->Img->height();
    this->depth = this->Img->depth();
    this->spectrum = this->Img->spectrum();
}
Image::Image (const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, int value)
Image (const char *const filename) this constructor is used when the image already exist's and is stored in.
This constructor is used when we need to create an image, and gives the dimensions of the image, and the value of a color that fills all the pixels.
Parameters
filename.
Definition at line 49 of file image.cpp.
{
    this->Img = new CImg<unsigned char>(width, height, depth, spectrum, value);
    this->width = width;
    this->height = height;
    this->depth = depth;
    this->spectrum = spectrum;
}
Image::~Image (void)
Image (const unsigned int width, const unsigned int height, const unsigned int depth, const unsigned int spectrum, int value) This constructor is used when we try to create an image with the specified dimensions and the parameter
Parameters
value is the value of the color of all the pixels of the image.
Definition at line 60 of file image.cpp.
{
    
}
Member Function Documentation
CImg< float > Image::autocovariance (int hor_dis, int ver_dis, int num_threads)
Calculates the autocovariance matrix for the image. The covariance, calculates the covariance matrix of an image. This function calculates something similar to the function below: $ g(x,y) = \sum \limits_{n=0}^{N} \sum \limits_{m=1}^M \left( f(x,y) - \overline{f(x,y)}\right)\left(f(x + \Delta x, y + \Delta y) - \overline{f(x + \Delta x, y + \Delta y)} \right) $ Where it calculates the variation between two series, one is the normal one, and the other is displaced by two parameters $ x$ & $ y$. For an image it its calculated for a neighborhood around each pixel.
Returns
A CImg object, because it must contain float values.
Definition at line 2047 of file image.cpp.
{
    CImg<float> autocovariance (this->get_width() , this->get_height(), this->get_depth(),
      this->get_spectrum(), 0);
    
    Image average = this->filter_average(1);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 3+hor_dis; x < this->get_width()-(3+hor_dis); x++)
            {
                for(unsigned int y = 3+ver_dis; y < this->get_height()-(3+ver_dis); y++)
                {
                    int sum = 0;
                    for(unsigned int i = x-3; i<x+4; i++)
                    {
                        for(unsigned int j= y-3; j<y+4; j++)
                        {
                            sum += ((this->get_pixel_value(i,j,z,c)) - average.get_pixel_value(i,j,z,c))
       * ((this->get_pixel_value(i+hor_dis,j+ver_dis,z,c)) - average.get_pixel_value(i+hor_dis,j+ver_dis,z,c))
      ;
                        }
                    }
                
                    autocovariance(x,y,z,c) = sum/49;
                }
            }
        }
     }
    return autocovariance;
}
Image Image::average_omp (int , int)
Image Image::binarize_img (unsigned int cutoff_value, int num_threads)
Definition at line 301 of file image.cpp.
{
    Image result (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel= static_cast<unsigned int>(this->get_pixel_value(x,y,z,c));
                    if(pixel >= cutoff_value)
                        pixel=255;
                    else
                        pixel=0;
                    result.set_pixel_value(x,y,z,c,pixel);
                }
            }
        }
    }
    
    return result;
}
Image Image::color_slicing (unsigned char color1[], unsigned char color2[], unsigned char neutral[], int num_threads)
Highlights the desired colors, between the two colors given as parameters.
Attention
{The colors must be unsigned char, and must be the size of the spectrum of the image (Number of channels), 3 in case o RBG images}
Parameters
unsigned char color1[]: The start color of the color slicing.
unsigned char color2[]: The end color of the color slicing.
unsigned char neutral: The intensity every other pixels that are not between the given colors will be set to.
Definition at line 1124 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel = this->get_pixel_value(x,y,z,c);
                    if(pixel > color1[c] && pixel < color2[c])
                    {
                        filtered.set_pixel_value(x, y, z, c, pixel);
                    }
                    else
                    {
                        filtered.set_pixel_value(x,y,z,c, neutral[c]);
                    }
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::coorrelogram (unsigned int ver, unsigned int hor, int num_threads)
This function compute the coorrelogram of an image.
This function compute the coorrelogram of a specified depth and spectrum of an image.
Parameters
unsigned int ver is the vertical distance of the original pixel that we use to compute the coorrelogram.
unsigned int hor is the horizontal distance of the original pixel that we use to compute the coorrelogram.
Returns
This function returns the coorrelogram image.
Parameters
unsigned int ver is the vertical distance of the original pixel that we use to compute the coorrelogram.
unsigned int hor is the horizontal distance of the original pixel that we use to compute the coorrelogram.
unsigned int z is the specified depth of the image that will be obtained the coorrelogram.
unsigned int c is the specified spectrum of the image that will be obtained the coorrelogram.
Returns
This function returns the coorrelogram image.
Definition at line 2164 of file image.cpp.
{
    
    Image result (256,256, 1, 1, 0);
    
    for(unsigned int i = 0; i < 256; i++)
    {
        for(unsigned int j=0; j< 256; j++)
        {
            unsigned int pixel = 0;
            
            for(unsigned int x=0; x< (this->get_width()-hor);++x)
            {
                
                for(unsigned int y=0; y< (this->get_height()-ver);++y)
                {
                    unsigned char first = (this->get_pixel_value(x,y,0,0));
                    unsigned char secnd = (this->get_pixel_value(x+hor, y+ver, 0, 0));
                    
                    if(first == i && secnd == j)
                    {
                        pixel ++;
                    }
                }
            }
            if(pixel>255)
            {
                pixel=255;
            }
            
            result.set_pixel_value(i, j, 0, 0, pixel);
            
        }
        
        cout<<"\n"<<i<<"\n"<<endl;
    }
    return result;
}
Image Image::coorrelogram_par (unsigned int, unsigned int, unsigned int, unsigned int)
Image Image::coorrelogram_ZC (unsigned int ver, unsigned int hor, unsigned int z, unsigned int c, int num_threads)
Definition at line 2212 of file image.cpp.
{
    
    Image result (256,256, 1, 1, 0);
    
    for(unsigned int i = 0; i < 256; i++)
    {
        for(unsigned int j=0; j< 256; j++)
        {
            unsigned int pixel = 0;
            
            for(unsigned int x=0; x< (this->get_width()-hor);++x)
            {
                
                for(unsigned int y=0; y< (this->get_height()-ver);++y)
                {
                    unsigned char first = (this->get_pixel_value(x,y,z,c));
                    unsigned char secnd = (this->get_pixel_value(x+hor, y+ver, z, c));
                    if(first == i && secnd == j)
                    {
                        pixel ++;
                    }
                }
            }
            if(pixel>255)
            {
                pixel=255;
            }
            result.set_pixel_value(i, j, 0, 0, pixel);
            
        }
        
    }
    return result;
}
void Image::display (const char * message)
Definition at line 77 of file image.cpp.
{
    CImgDisplay main (*(this->Img), message);
    while(!main.is_closed())
    {
        main.wait();
    }
}
Image Image::filter_average (int dim, int num_threads)
This function calculates the average of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Parameters
Only receives the dimension of the kernel (dim), wich only can be an impair number.
Returns
Image filtered which is the image with the average filter applied.
Definition at line 803 of file image.cpp.
Referenced by autocovariance().
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = dim; x < this->get_width()-dim; x++)
            {
                for(unsigned int y = dim; y < this->get_height()-dim; y++)
                {
                    int sum = 0;
                    for(unsigned int i = x-dim; i<= x+dim; i++)
                    {
                        for(unsigned int j = y-dim; j<= y+dim; j++)
                        {
                            sum += this->get_pixel_value(i, j, z, c);
                        }
                    }
            
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (sum/((dim*2+1)*(dim*2+
      1)));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_dynamic_range_dilatation (unsigned char a, unsigned char b, double alpha, double beta, double gamma, int num_threads)
All the pixel values are divided in 3 ranges, and each range suffer a diferent transformation. This function is used to transform the range of lower pixel values in medium values and the higher too, to smooth the image.
Parameters
unsigned char a is the first cutoff pixel value.
unsigned char b is the second cutoff pixel value.
double alpha is the first multiplier.
double beta is the second multiplier.
double gamma is the third multiplier.
Returns
An image object that contains the dilatated image.
Definition at line 1052 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel=0;
                    
                    if(this->get_pixel_value(x,y,z,c)<a)
                        pixel =abs(alpha*this->get_pixel_value(x,y,z,c));
                        
                    else if(this->get_pixel_value(x,y,z,c)>=a && this->get_pixel_value(x,y,z,c)<b)
                        pixel=abs(beta*(this->get_pixel_value(x,y,z,c)-a)+alpha*a);
                    
                    else if(this->get_pixel_value(x,y,z,c)<=b)
                        
                        pixel=abs(gamma*(this->get_pixel_value(x,y,z,c)-b)+((beta*(b-a))+alpha*a));
                    filtered.set_pixel_value(x,y,z,c,static_cast<unsigned int>(pixel));
                }
            }
        }
    }
    return filtered;
}
Image Image::filter_edge_enhacement_displacement (unsigned int horizontal_dis, unsigned int vertical_dis, int num_threads)
Definition at line 662 of file image.cpp.
{
    Image result (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0);
       
    if((horizontal_dis < this->get_width()) && (vertical_dis < this->get_height()))
    {
        for(unsigned int c = 0; c < this->get_spectrum(); c++)
        {
            for(unsigned int z = 0; z < this->get_depth(); z++)
            {
                for(unsigned int x = horizontal_dis; x < this->get_width(); x++)
                {
                    for(unsigned int y = vertical_dis; y < this->get_height(); y++)
                    {
                        unsigned char value = static_cast<unsigned char>(abs(this->get_pixel_value(x,y,z,c)
       - this->get_pixel_value(x-horizontal_dis, y-vertical_dis, z, c)));
                        
                        result.set_pixel_value(x,y,z,c, value);
                    }
                }
            }
        }
    }
    return result;
}
Image Image::filter_freeman_0 (int num_threads)
Applies the freeman mask $(1,1,1)(1,-2,1)(1,-1,-1)$.
Definition at line 1510 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x+1,y,z,c))-
      1*(get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_1 (int num_threads)
Applies the freeman mask $(1,1,1)(-1,-2,1)(1,-1,1)$.
Definition at line 1545 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x+1, y+1, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x+1,y,z,c)
      )-1*(get_pixel_value(x-1, y, z, c)+get_pixel_value(x, y+1, z, c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_2 (int num_threads)
Applies the freeman mask $)-1,1,1)(-1,-2,1)(1,1,1)$.
Definition at line 1580 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c)+
      get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c)+get_pixel_value(x-1,y+1,z,c))-
      1*(get_pixel_value(x-1, y, z, c)+get_pixel_value(x-1, y-1, z, c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_3 (int num_threads)
Applies the freeman mask $(-1,-1,1)(-1,-2,1)(1,1,1)$.
Definition at line 1615 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x+1, y, z, c)+
      get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c)+get_pixel_value(x-1,y+1,z,c))-1*(get_pixel_value(x-1, y, z,
      c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x-1,y-1,z,c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_4 (int num_threads)
Applies the freeman mask $(-1,-1,-1)(1,-2,1)(1,1,1)$.
Definition at line 1650 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y, z, c)+get_pixel_value(x-1, y+1, z, c)+
      get_pixel_value(x, y+1, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x+1, y, z, c))-1*(get_pixel_value(x-1, y-1,
      z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1,y-1,z,c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_5 (int num_threads)
Applies the freeman mask $(1,-1,-1)(1,-2,-1)(1,1,1)$.
Definition at line 1686 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y+1, z, c)+get_pixel_value(x+1, y+1, z, c))-1*(get_pixel_value(x+1, y,
      z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1,y-1,z,c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_6 (int num_threads)
Applies the freeman mask $(1,1,-1)(1,-2,-1)(1,1,-1)$.
Definition at line 1722 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y+1, z, c)+get_pixel_value(x, y-1, z, c))-1*(get_pixel_value(x+1, y-1,
      z, c)+get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1,y+1,z,c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_freeman_7 (int num_threads)
Applies the freeman mask $(1,1,1)(1,-2,-1)(1,-1,-1)$.
Definition at line 1757 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = (get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x, y-1, z, c))-1*(get_pixel_value(x, y+1,
      z, c)+get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1,y+1,z,c))+-2*get_pixel_value(x, y, z, c);
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_gaussian (int o, int dim_kernel, int num_threads)
This function applies a gaussian kernel trough the hole image.
Parameters
Receives the dimension of the kernel (dim_kernel) and a paremeter o wich stablish the values on the gaussian kernel.
Returns
Image filtered which is the image with the gaussian filter applied.
Definition at line 841 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    double kernel[dim_kernel*dim_kernel];
    
    int m = (dim_kernel-1)/2;
    
    double gaussian =1/pow(3.1415*2*o*o,0.5);
    for(int i =-m; i <=m; i++)
    {
        for(int j =-m; j<=+m; j++)
        {
            double exp= -(i*i+j*j)*0.5/(o*o);
            kernel[(i+m)*dim_kernel + (j+m)]=gaussian*pow(2.7,exp);
            
        }
    }
    
    
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width(); x++)
            {
                for(unsigned int y = m; y < this->get_height(); y++)
                {
                    int cont=0;
                    unsigned char pixel=0;
                    
                    for(unsigned int i = x-m; i < x+m; i++)
                    {
                        for(unsigned int j = y-m; j< y+m; j++)
                        {
                            pixel+= this->get_pixel_value(i, j, z, c)*(kernel[cont]);
                            cont++;
                        }
                    }
                    filtered.set_pixel_value(x, y, z, c, (pixel/2));
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_Gradient_horizontal (int num_threads)
This filter is used as as Sharpening Spatial Filter, used to identify borders and noise in the image. Can be used to identify horizontal borders or discrepation Applies the following filter: $ ((1, 2, 1) , (0, 0, 0) , (-1, -2, -1)) $
Returns
An image object that contains the original image after receiving a gradient filter in the horizontal direction. Could be used to identify horizontal borders.
Definition at line 436 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = this->get_pixel_value(x-1, y-1, z, c) + 2*(this->get_pixel_value(x, y-1, z, c
      )) + this->get_pixel_value(x+1, y-1, z, c) - (this->get_pixel_value(x-1, y+1, z, c) + 2*(this->
      get_pixel_value(x, y+1, z, c)) + this->get_pixel_value(x+1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_Gradient_vertical (int num_threads)
This filter is used as as Sharpening Spatial Filter, used to identify borders and noise in the image. Can be used to identify vertical borders or discrepations. Applies the following filter: $ ((1, 0, -1) , (2, 0, -2) , (1, 0, -1)) $
Returns
An image object that contains the original image after receiving a gradient filter in the vertical direction. Could be used to identify vertical borders.
Definition at line 473 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = get_pixel_value(x-1, y-1, z, c) + 2*get_pixel_value(x-1, y, z, c) +
      get_pixel_value(x-1, y+1, z, c) - (get_pixel_value(x+1, y-1, z, c) + 2*get_pixel_value(x+1, y, z, c) +
      get_pixel_value(x+1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_horizontal_borders (int num_threads)
Definition at line 711 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(this->
      get_pixel_value(x, y-1, z, c) - get_pixel_value(x, y+1, z, c)));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_kirsch_0 (int num_threads)
Applies the kirsch mask at 0°. $(-3,-3,5)(-3,0,5)(-3,-3,5)$.
Definition at line 1228 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x, y+1, z, c))+5*(get_pixel_value(x+1, y-
      1, z, c)+get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_135 (int num_threads)
Applies the kirsch mask at 135°. $(5,5,-3)(5,0,-3)(-3,-3,-3)$.
Definition at line 1335 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x+1, y, z, c)+
      get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c)+get_pixel_value(x-1, y+1, z, c))+5*(get_pixel_value(x-1,
      y, z, c)+get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x, y-1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_180 (int num_threads)
Applies the kirsch mask at 180°. $(5,-3,-3)(5,0,-3)(5,-3,-3)$.
Definition at line 1370 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c)+
      get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c))+5*(get_pixel_value(x-1, y,
       z, c)+get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x-1, y-1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_225 (int num_threads)
Applies the kirsch mask at 225°. $(-3,-3,-3)(5,0,-3)(5,5,-3)$.
Definition at line 1405 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x, y-1, z, c)+
      get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x+1, y, z, c)+get_pixel_value(x+1, y+1, z, c))+5*(get_pixel_value(x-1,
      y, z, c)+get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_270 (int num_threads)
Applies the kirsch mask at 270°. $(-3,-3,-3)(-3,0,-3)(5,5,5)$.
Definition at line 1440 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c)+get_pixel_value(x+1, y, z, c))+5*(get_pixel_value(x, y+1,
       z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x-1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_315 (int num_threads)
Applies the kirsch mask at 315°. $(-3,-3,-3)(-3,0,5)(-3,5,5)$.
Definition at line 1475 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x+1, y-1, z, c))+5*(get_pixel_value(x, y+
      1, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x+1, y, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_kirsch_45 (int num_threads)
Applies the kirsch mask at 45°. $(-3,5,5)(-3,0,5)(-3,-3,-3)$.
Definition at line 1264 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y-1, z, c)+get_pixel_value(x-1, y, z, c)+
      get_pixel_value(x-1, y+1, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x, y+1, z, c))+5*(get_pixel_value(x+1,
      y-1, z, c)+get_pixel_value(x+1, y, z, c)+get_pixel_value(x, y-1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
    
}
Image Image::filter_kirsch_90 (int num_threads)
Applies the kirsch mask at 90°. $(5,5,5)(-3,0-3)(-3,-3,-3)$.
Definition at line 1300 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = -3*(get_pixel_value(x-1, y, z, c)+get_pixel_value(x-1, y+1, z, c)+
      get_pixel_value(x, y+1, z, c)+get_pixel_value(x+1, y+1, z, c)+get_pixel_value(x+1, y, z, c))+5*(get_pixel_value(x+1, y-
      1, z, c)+get_pixel_value(x, y-1, z, c)+get_pixel_value(x-1, y-1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_Laplacian (int num_threads)
Returns an image after applying the Laplacian filter to the image. Considers the diagonal values This function applies a convolution with this kernel: $ ((1, 1, 1), (1, -8, 1), (1, 1, 1)) $.
Returns
A Filtered image with the Laplacian filter applied.
Definition at line 347 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = 0;
                    
                    for (unsigned int i = 0 ; i < 3; i++)
                    {
                        for(unsigned int j = 0 ; j < 3; j++)
                        {
                        sum += -this->get_pixel_value(x+i-1, y+i-1, z, c);
                        }
                    }
                    
                    sum += 9*(this->get_pixel_value(x,y,z,c));
                    
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    return filtered;
}
Image Image::filter_Laplacian_no_diagonal (int num_threads)
Works as a derivative function, reacts to high change on the pixels value, especially to noise, and borders. Applies the following filter: $ ((0, -1, 0) , (-1, 4, -1) , (0, -1, 0)) $
Returns
A filtered Image with the laplacian filter.
Definition at line 393 of file image.cpp.
{
    //int kernel[9] = {0, -1, 0, -1, 4, -1, 0, -1, 0};
    
    //return (this->filter(kernel, 3, 1));
    
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = 4*(this->get_pixel_value(x,y,z,c)) - (this->get_pixel_value(x-1,y,z,c) +
      this->get_pixel_value(x+1,y,z,c) + this->get_pixel_value(x,y-1,z,c) +this->get_pixel_value(x,y+1,z,c));
                    
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    return filtered;
    
}
Image Image::filter_maximum (int num_threads)
Assigns the highest value in the neighborhood. Assigns the highest value in the neighborhood around the desired pixel.
Definition at line 1795 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 1; x < this->get_width()-1; x++)
            {
                for(unsigned int y = 1; y < this->get_height()-1; y++)
                {
                    unsigned char max = 0;
                    
                    for (unsigned int i = x-1; i< x+2; i++)
                    {
                        for (unsigned int j = y-1; j< y+2; j++)
                        {
                            unsigned char pixel = (this->get_pixel_value(i, j, z, c));
                             
                            if (pixel > max)
                            {
                                max = this->get_pixel_value(i, j, z, c);
                            }
                        }
                    }
                    
                    filtered.set_pixel_value(x, y, z, c, max);
                }
                
             }
             
         }
    }
    return filtered;
}
Image Image::filter_median (int dim, int num_threads)
This function calculates the median of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Parameters
Only receives the dimension of the kernel (dim), wich only can be an impair number.
Returns
Image filtered which is the image with the median filter applied.
Definition at line 747 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    //int kernel [dim*dim];
    int m = (dim-1)/2;
    unsigned char pixel_values [dim*dim];
    unsigned char temp;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width(); x++)
            {
                for(unsigned int y = m; y < this->get_height(); y++)
                {
                    for(unsigned int i = x-m; i < x+m; i++)
                    {
                        for(unsigned int j = y-m; j< y+m; j++)
                        {
                            pixel_values [(i-x+m)*dim + (j-y+m)]= this->get_pixel_value(i, j, z, c);
                            
                        }
                    }
                    for(int k=0; k<dim*dim ; k++)
                    {
                        for(int p=k+1 ; p<dim*dim ; p++)
                        {
                            if(pixel_values[p] < pixel_values[k])
                            {
                            // Intercambiar los valores
                            temp = pixel_values[k];
                            pixel_values[k] = pixel_values[p];
                            pixel_values[p] = temp;
                            }
                        }
                    }
                    unsigned char pixel = pixel_values[((dim*dim-1)/2)-1];
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
 }
Image Image::filter_minimum (int num_threads)
Assigns the highest value in the neighborhood.
Definition at line 1838 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 1; x < this->get_width()-1; x++)
            {
                for(unsigned int y = 1; y < this->get_height()-1; y++)
                {
                    unsigned char minimun = 255;
                    
                    for (unsigned int i = x-1; i< x+2; i++)
                    {
                        for (unsigned int j = y-1; j< y+2; j++)
                        {
                            if ((this->get_pixel_value(i, j, z, c)) < minimun)
                            {
                                minimun = this->get_pixel_value(i, j, z, c);
                            }
                        }
                    }
                    
                    filtered.set_pixel_value(x, y, z, c, minimun);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_modal (int dim, int num_threads)
This function calculates the modal of the range of pixels into the kernel and sets this value in the central pixel of the kernel.
Parameters
Only receives the dimension of the kernel (dim), wich only can be an impair number.
Returns
Image filtered which is the image with the modal filter applied.
Definition at line 898 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    unsigned char pixel_values[dim*dim];
    unsigned char moda;
    unsigned char average=0;
    int m=(dim-1)/2;
    unsigned char copy_pixels[dim*dim];
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width(); x++)
            {
                for(unsigned int y = m; y < this->get_height(); y++)
                {
                    for(unsigned int i = x-m; i < x+m; i++)
                    {
                        for(unsigned int j = y-m; j< y+m; j++)
                        {
                            pixel_values [(i-x+m)*dim + (j-y+m)]= this->get_pixel_value(i, j, z, c);
        
                            int frequency[dim*dim];
                            moda=0;
                            
                            for(int k=0;k<dim*dim;k++)
                            {
                                copy_pixels[k]= pixel_values[k];
                                frequency[k]=0;
                            }
                            
                            for(int p=0;p<dim*dim;p++)
                            {
                                for(int q=p+1;q<dim*dim;q++)
                                {
                                    if(copy_pixels[p]==pixel_values[q]){
                                        frequency[p]++;
                                
                                    }
            
                                }
    
                            }
                            for(int s=0; s<dim*dim ; s++)
                            {
                                for(int e=s+1 ; e<dim*dim ; e++)
                                {
                                    if(frequency[e] < frequency[s])
                                    {
                                        moda = copy_pixels[s];
                                        average=copy_pixels[s];
                                    }
                                }
                            }
                            
                            if(moda==0)
                            {
                                for(int k=0;k<dim*dim;k++)
                                {
                                    moda += pixel_values[k];
                                }
                            average=(moda/dim);
                            }
                        }
                    }
                    
                    filtered.set_pixel_value(x, y, z, c, average);
                }
                
             }
             
         }
    }
return filtered;
}
Image Image::filter_order_stadistics (int dim, int order, int num_threads)
Definition at line 1873 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    //int kernel [dim*dim];
    
    int m = (dim-1)/2;
    
    unsigned char pixel_values [dim*dim];
    unsigned char temp;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width(); x++)
            {
                for(unsigned int y = m; y < this->get_height(); y++)
                {
                    for(unsigned int i = x-m; i < x+m+1; i++)
                    {
                        for(unsigned int j = y-m; j< y+m+1; j++)
                        {
                            pixel_values [(i-x+m)*dim + (j-y+m)]= this->get_pixel_value(i, j, z, c);
                            
                        }
                    }
                    for(int k=0; k<dim*dim ; k++)
                    {
                        for(int p=k+1 ; p<dim*dim ; p++)
                        {
                            if(pixel_values[p] < pixel_values[k])
                            {
                            // Intercambiar los valores
                            temp = pixel_values[k];
                            pixel_values[k] = pixel_values[p];
                            pixel_values[p] = temp;
                            }
                        }
                    }
                    unsigned char pixel = pixel_values[order];
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
Image Image::filter_Prewitt_E_W (int num_threads)
Definition at line 590 of file image.cpp.
{
    //int kernel[9] = {1, 0, -1, 1, 0, -1, 1, 0, -1};
    
    //return (this->filter(kernel, 3, 1));
    
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = get_pixel_value(x-1, y-1, z, c) + get_pixel_value(x-1, y, z, c) +
      get_pixel_value(x-1, y+1, z, c) - (get_pixel_value(x+1, y-1, z, c) + get_pixel_value(x+1, y, z, c) + get_pixel_value(x+
      1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_Prewitt_N_S (int num_threads)
Definition at line 520 of file image.cpp.
{
    //int kernel[9] = {1, 1, 1, 0, 0, 0, -1, -1, -1};
    
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = get_pixel_value(x-1, y-1, z, c) + get_pixel_value(x, y-1, z, c) +
      get_pixel_value(x+1, y-1, z, c) - (get_pixel_value(x-1, y+1, z, c) + get_pixel_value(x, y+1, z, c) + get_pixel_value(x+
      1, y+1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_Prewitt_NE_SW (int num_threads)
Definition at line 554 of file image.cpp.
{
    //int kernel[9] = {0, 1, 1, -1, 0, 1, -1, -1, 0};
    
    //return (this->filter(kernel, 3, 1));
    
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = get_pixel_value(x, y-1, z, c) + get_pixel_value(x+1, y-1, z, c) +
      get_pixel_value(x+1, y, z, c) - (get_pixel_value(x-1, y, z, c) + get_pixel_value(x-1, y+1, z, c) + get_pixel_value(x, y
      +1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
    
}
Image Image::filter_Prewitt_NW_SE (int num_threads)
Definition at line 626 of file image.cpp.
{
    //int kernel[9] = {-1, -1, 0, -1, 0, 1, 0, 1, 1};
    
    // (this->filter(kernel, 3, 1));
    
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = m; y < this->get_height()-m; y++)
                {
                    int sum = get_pixel_value(x-1, y-1, z, c) + get_pixel_value(x-1, y, z, c) +
      get_pixel_value(x, y-1, z, c) - (get_pixel_value(x+1, y, z, c) + get_pixel_value(x+1, y+1, z, c) + get_pixel_value(x, y
      +1, z, c));
                    if (sum > 255 || sum < -255)
                    {
                        sum = 255;
                    }
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(sum));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    
    return filtered;
        
}
Image Image::filter_vertical_borders (int num_threads)
Definition at line 686 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    int m = 1;
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = m; x < this->get_width()-m; x++)
            {
                for(unsigned int y = 0; y < this->get_height()-m; y++)
                {
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (abs(this->
      get_pixel_value(x-1, y, z, c) - get_pixel_value(x+1, y, z, c)));
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
void Image::gaussian_noise (double variance, int num_threads)
Converts an RGB image to gray scale.
This function applies the gaussian noise to an image. The gaussian noise increases or decreases intensity to a pixel, depending of the variance.
Parameters
variance this parameter is used to set the value of noise that is applied to the image.
Definition at line 1970 of file image.cpp.
{
    srand(1);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    double random= variance*(rand()-RAND_MAX/variance)/RAND_MAX;
                    unsigned char pixel= this->get_pixel_value(x,y,z,c) + random;
                    
                    if((pixel<255) & (pixel>0))
                    {
                        (*(this->Img))(x, y, z, c)= pixel;
                    }
                }
                
                
             }
             
         }
    }
     
}
int * Image::get_histogram (unsigned int c, unsigned int z)
This function returns an array containing the values of the histogram points, in the desired channel and depth. An Histogram is measure of the frecquency of a intensity value in an image, and is often used as a parameter to improve the constrast and quality of the image. After observing the histogram (see plot_histogram()) you could ecualizate the image.
Definition at line 1167 of file image.cpp.
{
    int histogram [256];
    for(int i = 0; i<256; i++)
    {
    histogram[i] = 0;
    }
    
    if (c < this->get_spectrum() && z < this->get_depth())
    {
        for(unsigned int x = 0; x < this->get_width(); x++)
        {
            for(unsigned int y = 0; y < this->get_height(); y++)
            {
                unsigned char pixel_value = this->get_pixel_value(x,y,z,c);
                (histogram[pixel_value])++;
            }
        }
    }
    
    int* histogram_pointer = histogram;
    
    return histogram_pointer;
}
Image Image::gray_scale (int num_threads)
Assigns the lowest value in the neighborhood.
This function converts an RGB image to one in gray scale. The library uses this conversion: f(x,y)= 0.11R+0.56G + 0.14B Where f is the intensity of the pixel on the gray scale and R,G and B the pixel values on the different channels.
Returns
This function returns the mochromathic image.
Definition at line 2136 of file image.cpp.
{
    Image gray_image (this->get_width() , this->get_height(), this->get_depth(), 1, 0);
    for(unsigned int z = 0; z < this->get_depth(); z++)
    {
        for(unsigned int x = 0; x < this->get_width(); x++)
        {
            for(unsigned int y = 0; y < this->get_height(); y++)
            {
            
                unsigned char pixel_intensity = 0.56*this->get_pixel_value(x,y,z,1)+0.14*this->
      get_pixel_value(x,y,z,0)+0.11*this->get_pixel_value(x,y,z,2);
                gray_image.set_pixel_value(x, y, z, 0, pixel_intensity);
                
            }
             
         }
    }
     return gray_image;
}
int* Image::histogram_equalization (int * , const char * title)
Image Image::interpolation (int num_threads)
This function doubles the size of the image and use the closer neighborhood interpolation.
Returns
This function returns the image interpolated.
Definition at line 2005 of file image.cpp.
{
    int i,j=0;
    Image result (2*this->get_width(),2*this->get_height(),this->get_depth(),this->get_spectrum(),0);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int y = 0; y < this->get_width(); y++)
            {
                for(unsigned int x = 0; x < this->get_height(); x++)
                {
                    unsigned char pixel=this->get_pixel_value(x,y,z,c);
                    
                    result.set_pixel_value(x+i,y+j,z,c,pixel);
                    result.set_pixel_value(x+1+i,y+j,z,c,pixel);
                    result.set_pixel_value(x+i,y+1+j,z,c,pixel);
                    result.set_pixel_value(x+1+i,y+1+j,z,c,pixel);
                    i++;
                }
                i=0;
                j++;
            }
            j=0;
        }
    }
    return result;
}
Image Image::inverse (int num_threads)
Executes this transformation: $ v(x,y,z,c) = 255 - u(x,y,z,c) $
Returns
An image object that contains the inverse of the original image, this means that every pixel value is substracted to 255.
Definition at line 994 of file image.cpp.
{
    Image inverted (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel= static_cast<unsigned int>(255-this->get_pixel_value(x,y,z,c));
                    inverted.set_pixel_value(x,y,z,c,pixel);
                }
            }
        }
    }
    return inverted;
}
Image Image::log_transformation (int num_threads)
Executes this transformation: $ v(x,y,z,c) = c log(u(x,y,z,c)+1)$ where v(x,y,z,c) is the transformed pixel, and u(x,y,z,c) is the original pixel.
Returns
An image object that contains the inverse of the original image, this means that every pixel value is substracted to 255.
Definition at line 1020 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel = static_cast<unsigned char>((255/log(256)) * log(1+this->
      get_pixel_value(x, y, z, c)));
                    
                    filtered.set_pixel_value(x,y,z,c, pixel);
                }
            }
        }
    }
    return filtered;
}
Image Image::median_omp (int , int)
Image Image::multiply_img (double multiplier, int num_threads)
This function multiplies the pixel values by a factor. If the pixel value is higher than 255, adjust the pixel value to 255.
Parameters
double multiplier is the factor that mutiplies all the pixel values.
Returns
Image result: Is the result of multiply the image.
Definition at line 273 of file image.cpp.
{
    Image result (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    unsigned char pixel= static_cast<unsigned int>(abs(this->get_pixel_value(x,y,z,c)*
      multiplier));
                    if (pixel >255)
                        pixel = 255;
                    result.set_pixel_value(x,y,z,c,pixel);
                }
            }
        }
    }
    return result;
}
void Image::plot_histogram (int levels, const char * title)
This function plot the histogram, using the CImg histogram function.
Parameters
levels is the number of bars or columns that appear in the histogram.
title is the title of the histogram.
Definition at line 1197 of file image.cpp.
{
    CImg<unsigned char> img = this->Img->histogram(levels);
    
    CImgDisplay main_display (*(this->Img), title);
    
    img.display_graph(main_display, 3, 1, "Pixel Intensity", 0, 0, "Frequency", 0, 0);
}
void Image::plot_histogram_equalization (int levels, const char * title)
Definition at line 1211 of file image.cpp.
{
    CImg<unsigned char> img = this->Img->equalize(levels);
    
    CImgDisplay main_display (*(this->Img), title);
    
    img.display_graph(main_display, 3, 1, "Pixel Intensity", 0, 0, "Frequency", 0, 0);
}
Image Image::power_law_transformatiom (double exponent, int num_threads)
Executes this transformation: $ v(x,y,z,c) = c log(u(x,y,z,c)+1)$.
Applies a transformation given by the ecuation $ v(x,y) = c {u(x,y)}^{\gamma} $ where $ u(x,y) $ is the value of the non filtered image, and $ v(xy) $ is the intensity value in the filtered image. $ \gamma, c $ are constants. In this case $ \gamma $ is a parameter.
Returns
A filtered image with the power law transformation
Definition at line 1091 of file image.cpp.
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    double k = (pow(255, 1-exponent));
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    double power_law = k * pow((this->get_pixel_value(x,y,z,c)) , exponent);
                    unsigned char pixel = static_cast<unsigned char>(power_law);
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
    return filtered;
}
Image Image::rgb_hsv ()
void Image::salt_pepper (double intensity, int num_threads)
Put pepper (black pixels) and salt(white pixels)
Parameters
intensity is used to compute the percentage of salt and pepper that is applied to the image.
Definition at line 1933 of file image.cpp.
{
    srand(1);
    double percentage = 1-(intensity/100);
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = 0; x < this->get_width(); x++)
            {
                for(unsigned int y = 0; y < this->get_height(); y++)
                {
                    double random= 2.0*(rand()-RAND_MAX/2.0)/RAND_MAX;
                    if(random > percentage)
                    {
                        (*(this->Img))(x, y, z, c)= 255;
                    }
                    else if(random<-1*percentage)
                    {
                        (*(this->Img))(x, y, z, c)= 0;
                    }
                }
                
                
             }
             
         }
    }
     
}
void Image::set_pixel_value (int x, int y, int z, int c, unsigned char value)
Definition at line 139 of file image.cpp.
Referenced by binarize_img(), color_slicing(), coorrelogram(), coorrelogram_ZC(), filter_average(), filter_dynamic_range_dilatation(), filter_edge_enhacement_displacement(), filter_freeman_0(), filter_freeman_1(), filter_freeman_2(), filter_freeman_3(), filter_freeman_4(), filter_freeman_5(), filter_freeman_6(), filter_freeman_7(), filter_gaussian(), filter_Gradient_horizontal(), filter_Gradient_vertical(), filter_horizontal_borders(), filter_kirsch_0(), filter_kirsch_135(), filter_kirsch_180(), filter_kirsch_225(), filter_kirsch_270(), filter_kirsch_315(), filter_kirsch_45(), filter_kirsch_90(), filter_Laplacian(), filter_Laplacian_no_diagonal(), filter_maximum(), filter_median(), filter_minimum(), filter_modal(), filter_order_stadistics(), filter_Prewitt_E_W(), filter_Prewitt_N_S(), filter_Prewitt_NE_SW(), filter_Prewitt_NW_SE(), filter_vertical_borders(), gray_scale(), interpolation(), inverse(), log_transformation(), multiply_img(), power_law_transformatiom(), substract_img(), sum_img(), and variance().
{
    (*(this->Img))(x, y, z, c)= value;
}
Image Image::substract_img (Image image2, int num_threads)
This function substracts the pixel values of two images, that can be used to see the differences between them.
Parameters
Image image2: Is the image that will be substracted to the original image.
Returns
Image result: Is the result of the substraction of both images.
Definition at line 207 of file image.cpp.
{
    Image result (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0);
       
    if(this->get_width() == image2.get_width() && this->get_height() == image2.get_height() && this->
      get_depth() == image2.get_depth() && this->get_spectrum() == image2.get_spectrum())
    {
        for(unsigned int c = 0; c < this->get_spectrum(); c++)
        {
            for(unsigned int z = 0; z < this->get_depth(); z++)
            {
                for(unsigned int x = 0; x < this->get_width(); x++)
                {
                    for(unsigned int y = 0; y < this->get_height(); y++)
                    {
                        unsigned char pixel= static_cast<unsigned int>(abs(this->get_pixel_value(x,y,z,c)-
      image2.get_pixel_value(x,y,z,c)));
    
                        result.set_pixel_value(x,y,z,c,pixel);
                    }
                }
            }
        }
    }
    return result;
}
Image Image::sum_img (Image image2, int num_threads)
Definition at line 233 of file image.cpp.
{
    Image result (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0);
       
    if(this->get_width() == image2.get_width() && this->get_height() == image2.get_height() && this->
      get_depth() == image2.get_depth() && this->get_spectrum() == image2.get_spectrum())
    {
        for(unsigned int c = 0; c < this->get_spectrum(); c++)
        {
            for(unsigned int z = 0; z < this->get_depth(); z++)
            {
                for(unsigned int x = 0; x < this->get_width(); x++)
                {
                    for(unsigned int y = 0; y < this->get_height(); y++)
                    {
                        unsigned char pixel;
                        int sum = this->get_pixel_value(x,y,z,c)+image2.get_pixel_value(x,y,z,c);
                        if (sum <= 255)
                        {
                            pixel = static_cast<unsigned int>(sum);
                        }
                        else
                        {
                            pixel = 255;
                        }
                        result.set_pixel_value(x,y,z,c,pixel);
                    }
                }
            }
        }
    }
    return result;
}
Image Image::variance (int dim, int num_threads)
This function compute the variance of an image. The variance is gived by the summation of the average multiplied by the substraction of the average with the pixel value, squared.
Returns
This function returns the image interpolated.
Definition at line 2084 of file image.cpp.
Referenced by gaussian_noise().
{
    Image filtered (this->get_width() , this->get_height(), this->get_depth(), this->get_spectrum(), 0
      );
    
    for(unsigned int c = 0; c < this->get_spectrum(); c++)
    {
        for(unsigned int z = 0; z < this->get_depth(); z++)
        {
            for(unsigned int x = dim; x < this->get_width()-dim; x++)
            {
                for(unsigned int y = dim; y < this->get_height()-dim; y++)
                {
                    int sum = 0;
                    double variance=0;
                    int kernel_values[(dim*2+1)*(dim*2+1)];
                    int cont=0;
                    for(unsigned int i = x-dim; i<= x+dim; i++)
                    {
                        for(unsigned int j = y-dim; j<= y+dim; j++)
                        {
                            sum += this->get_pixel_value(i, j, z, c);
                            kernel_values[cont]=this->get_pixel_value(i, j, z, c);
                            cont++;
                        }
                    }
            
                    double average = sum/((dim*2+1)*(dim*2+1));
                    for(int i=0;i<(dim*2+1)*(dim*2+1);i++)
                    {
                        variance+=pow(kernel_values[i]-average,2)/((dim*2+1)*(dim*2+1));
                    }
                    
                    
                    unsigned char pixel = (unsigned char)static_cast<unsigned char> (variance);
                    filtered.set_pixel_value(x, y, z, c, pixel);
                }
                
             }
             
         }
    }
     return filtered;
}
The documentation for this class was generated from the following files:
/home/fish/Documents/ParallelPic/Proyecto/include/ParallelPic.hh
/home/fish/Documents/ParallelPic/Proyecto/src/image.cpp
/home/fish/Documents/ParallelPic/Proyecto/src/ParallelPic.cpp