.TH "/home/fish/Documents/ParallelPic/Proyecto/include/ParallelPic.hh" 3 "Mon Dec 9 2013" "Version 1.0" "ParallelPic" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/fish/Documents/ParallelPic/Proyecto/include/ParallelPic.hh \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/CImg\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <omp\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "\fIThe \fBImage\fP class is the abstraction of the image, contains a CImg object that defines the handling of the image\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ParallelPic from the source code\&.
